name: hisabx
description: "Spendrix - A modern, intuitive expense tracking app with dark theme support and comprehensive financial management features."
publish_to: 'none'

version: 1.3.0+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0+4
  path: ^1.8.0
  provider: ^6.0.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.0.15
  google_fonts: ^6.1.0
  path_provider: ^2.1.0
  share_plus: ^10.1.4
  pdf: ^3.10.0
  printing: ^5.12.02
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.8
  firebase_crashlytics: ^4.1.8
  firebase_auth: ^5.7.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/

flutter_gen:
  output: lib/gen/
  line_length: 80
  assets:
    enabled: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon.png"
